# Created on 05/02/2024
# UID="$(id -u)" GID="$(id -g)" sudo docker compose --env-file .env --env-file ~/.env up --no-deps --build -d
services:
  telegram-bot-api:
    image: heilkit/telegram-bot-api:latest
    entrypoint: telegram-bot-api -d "${STORAGE}" -v 1 --local --api-id="${API_ID}" --api-hash="${API_HASH}"
    restart: always
    network_mode: 'host'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1G'
    env_file:
      - .env
    user: ${UID}:${GID}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${STORAGE}:${STORAGE}
    environment:
      - API_ID
      - API_HASH
      - PORT
      - STORAGE
      - UID
      - GID